### ISSUE TITLE
Kernel won't compile when using jobs paramter (-j$(nproc))

### ISSUE THREAD

**Issue by Graphicscore** [radxa/rockpi4-android-tv-7.1#1]
When I try to compile the kernel it fails when using `-j$(nproc)` or `-j4`.

`make rk3399-rockpi-4b.img -j$(nproc)`
>   CHK     include/config/kernel.release
>   CHK     include/generated/uapi/linux/version.h
>   CHK     scripts/mod/devicetable-offsets.h
>   CHK     include/generated/utsrelease.h
> make[1]: *** No rule to make target 'arch/arm64/boot/dts/rockchip/rk3399-rockpi-4b.dtb'.  Stop.
> arch/arm64/Makefile:122: recipe for target 'rockchip/rk3399-rockpi-4b.dtb' failed
> make: *** [rockchip/rk3399-rockpi-4b.dtb] Error 2

However , running the command without the additional jobs parameters is compiling just fine
`make rk3399-rockpi-4b.img`

**Comment by hipboi** [comment]
Sorry for the confusion, the SDK is not yet finished pushing. I will let you know when it finishes and passes testing.

**Comment by Ahren-Li** [comment]
Hi Graphicscore
I have completed the code push, and tested sync code.
Please update your workspeace. This error will not exist.

**Comment by Graphicscore** [comment]
Awesome !

We're evaluating the RockPi at our company. Still waiting for the delivery of our board though.
Can't wait to test it out.

**Comment by Graphicscore** [comment]
I'm unable to build u-boot now. There is no config for rk3399_box_defconfig only for rk3399_defconfig

there is no `./mkv8.sh` either

`make rk3399_box_defconfig`
>   HOSTCC  scripts/basic/fixdep
>   HOSTCC  scripts/kconfig/conf.o
>   SHIPPED scripts/kconfig/zconf.tab.c
>   SHIPPED scripts/kconfig/zconf.lex.c
>   SHIPPED scripts/kconfig/zconf.hash.c
>   HOSTCC  scripts/kconfig/zconf.tab.o
>   HOSTLD  scripts/kconfig/conf
> ***
> *** Can't find default configuration "arch/../configs/rk3399_box_defconfig"!
> ***
> scripts/kconfig/Makefile:121: recipe for target 'rk3399_box_defconfig' failed
> make[1]: *** [rk3399_box_defconfig] Error 1
> Makefile:479: recipe for target 'rk3399_box_defconfig' failed
> make: *** [rk3399_box_defconfig] Error 2

**Comment by Ahren-Li** [comment]
Hi Graphicscore
I'm so sorry for this issue, Please try rock-pi-4b-rk3399_defconfig

**Comment by Ahren-Li** [comment]
Hi Graphicscore
I update the readme.
Thank you very much.
