### ISSUE TITLE
Would you like to release a version to support rock pro？

### ISSUE THREAD

**Issue by ustcjerry** [radxa/rockpi4-android-tv-7.1#2]
I'm an old fan of Radxa. I have bought a rockpro long time ago. I want to install android tv on my rockpro, but i have no idea to handle it.  So, would you like to release an image of android tv to work with rockpro?

**Comment by hipboi** [comment]
Hi, rock pro is based on rk3188 which is abandoned by Rockchip and going to EOL soon. I am sorry that we can not upgrade the Android for rock pro.

**Comment by ustcjerry** [comment]
I know it might be a tough procedure to do it myself, would you like to offer some tutorial and related materials about how to compile the android tv for rk3188?

**Comment by hipboi** [comment]
I have to say, there is no android tv for rk3188. For rk3188, Rockchip stopped updates since Android 5.1. I am sorry that we can not update it.

**Comment by hipboi** [comment]
Update: it seems Rockchip has newer Android support for PX3, which should be just rk3188, we will check it.

**Comment by ustcjerry** [comment]
Thank you for your support.  Looking forward from your good news.
